@host=http://localhost:3000

# ❌ "4000000000000002" - Simula falha no primeiro provedor - aprovado pelo segundo provedor
# ✅ exemplo de cartão de test sucesso - "4111111111111111"
### Criar uma cobrança
POST {{host}}/charges
Content-Type: application/json

{
  "merchantId": "1323",
  "orderId": "468ssedd8",
  "amount": 1500,
  "currency": "BRL",
  "description": "Pedido #erro",
  "paymentMethod": {
    "type": "credit",
    "installments": 1,
    "card": {
      "number": "4000000000009995",
      "holderName": "Erro",
      "cvv": "123",
      "expirationDate": "12/2025"
    }    
  }
}

### Listar cobranças
GET {{host}}/charges
?page=1
# &limit=8
# &merchantId=1323
# &orderId=4688
# &sort=asc

### Consultar cobrança por ID
GET {{host}}/charges/5b6289c0-28c9-4398-90c5-cd3fc0d5da62


### Estornar cobrança 
POST {{host}}/refunds/3587b968-c975-4c05-9ad0-04dd37760606
Content-Type: application/json

{
  "amount": 1000
}