@host=http://localhost:3000

###
# 💳 Criar uma cobrança
# 
# ❌ Número "4000000000000002" simula falha no primeiro provedor e força fallback para o segundo
# ✅ Número "4111111111111111" simula sucesso direto no primeiro provedor
###
POST {{host}}/charges
Content-Type: application/json

{
  "merchantId": "1323",
  "orderId": "789456",
  "amount": 1500,
  "currency": "BRL",
  "description": "Pedido #erro",
  "paymentMethod": {
    "type": "credit",
    "installments": 1,
    "card": {
      "number": "4000000000000002",
      "holderName": "Erro",
      "cvv": "123",
      "expirationDate": "12/2025"
    }    
  }
}

###
# 📋 Listar cobranças
# Paginação, filtro por merchantId, orderId , ordenação e limite  
###
GET {{host}}/charges
?page=1
# &limit=8
# &merchantId=1323
# &orderId=4688
# &sort=asc

###
# 🔍 Consultar cobrança por ID
###
GET {{host}}/charges/5b6289c0-28c9-4398-90c5-cd3fc0d5da62

###
# 🔄 Estornar cobrança
###
POST {{host}}/refunds/3587b968-c975-4c05-9ad0-04dd37760606
Content-Type: application/json

{
  "amount": 1000
}
