version: '3.8'

services:
  app:
    build: .
    container_name: pay_api_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always    
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
