version: '3.8'

services:
  app:
    build: .
    container_name: pay_api_app    
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/database
    ports:
      - "${APP_PORT}:3000"
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: pay_api_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"