version: '3.8'

services:
  app:
    build: .
    container_name: pay_api_app    
    depends_on:
      - db
    environment:      
      DB_URL: postgres://user:password@db:5432/database
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app      
    command: >
      sh -c "npm run prisma:db && npm run start:dev"
  db:
    image: postgres:15
    container_name: pay_api_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"